### PR TITLE
added coda normalized inversion

### PR DESCRIPTION
**Pull request by mlaaten**

### CODE REVIEW

**Comment by trichter** [comment]
Thank you! I'll have a look soonish.

**Comment by trichter** [comment]
Do we actually need the `"window_norm_smooth"` parameter? The envelope is normalized by an average in this window anyway. So options of e.g. `"coda_normalization": [180, 200]` would be enough, imho. Could you add this on top of my changes (git pull before you start working on this)? Please also add the commented example in the conf file.

**Comment by mlaaten** [comment]
I applied the changes and you are right, the parameter `"window_norm_smooth"` is not necessary, so I removed it.

**Comment by trichter** [comment]
Thanks for your first pull request!

**Pull request merged**
